// src/lib/components/CloseConfirmDialog.svelte
<script lang="ts">
  import Modal from "$lib/components/ui/Modal.svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import { hideToTray, quitApp } from "$lib/api/window-chrome";
  import { AlertCircle } from "@lucide/svelte";

  interface Props {
    open?: boolean;
    onCancel?: () => void;
  }

  let { open = false, onCancel }: Props = $props();

  let busy = $state(false);

  async function runBackground() {
    if (busy) return;
    busy = true;
    try {
      await hideToTray();
      onCancel?.();
    } catch (error) {
      console.error("[close-confirm] hide_to_tray failed", error);
    } finally {
      busy = false;
    }
  }

  async function runQuit() {
    if (busy) return;
    busy = true;
    try {
      await quitApp();
    } catch (error) {
      console.error("[close-confirm] quit_app failed", error);
      busy = false;
    }
  }
</script>

<Modal {open} onclose={onCancel} showClose={!busy} maxWidth="max-w-md">
  <div class="flex items-start gap-3.5">
    <div class="size-10 rounded-xl flex items-center justify-center shrink-0 bg-[var(--primary-soft)] text-[var(--primary)] border border-[var(--primary)]/20">
      <AlertCircle size={20} strokeWidth={2.2} />
    </div>
    <div class="min-w-0 flex-1">
      <h3 class="text-base font-semibold text-[var(--text-main)] tracking-tight">
        关闭 Coding Tools MCP?
      </h3>
      <p class="text-xs text-[var(--text-secondary)] mt-1.5 leading-relaxed">
        选择后台运行可隐藏窗口，保持正在运行的 MCP 与公网隧道服务持续可用；后续可通过系统托盘重新呼出。
      </p>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-2.5 pt-3 border-t border-[var(--border)]">
    <Button
      variant="ghost"
      size="md"
      disabled={busy}
      onclick={() => onCancel?.()}
    >
      取消
    </Button>
    <Button
      variant="secondary"
      size="md"
      disabled={busy}
      onclick={() => void runBackground()}
    >
      后台运行
    </Button>
    <Button
      variant="danger"
      size="md"
      {busy}
      onclick={() => void runQuit()}
    >
      彻底退出
    </Button>
  </div>
</Modal>

// src/components/CloseConfirmDialog.vue
<script setup lang="ts">
import { AlertCircle, X } from "@lucide/vue";
import { ref } from "vue";
import { hideToTray, quitApp } from "$lib/api/window-chrome";
import { showToast } from "$lib/stores/toast";

const open = defineModel<boolean>("open", { default: false });
const busy = ref(false);

async function run(action: "hide" | "quit") {
  if (busy.value) return;
  busy.value = true;
  try {
    if (action === "hide") await hideToTray();
    else await quitApp();
    open.value = false;
  } catch (error) {
    showToast(String(error), { title: "操作失败", kind: "error" });
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <Teleport to="body">
    <Transition name="modal">
      <div v-if="open" class="fixed inset-0 z-[1100] grid place-items-center bg-black/25 p-6 backdrop-blur-sm" @click.self="open = false">
        <div class="ios-glass-strong ios-floating-surface w-full max-w-md p-5">
          <div class="flex items-start gap-3">
            <div class="grid h-10 w-10 place-items-center rounded-2xl bg-[rgba(255,159,10,.14)] text-[var(--warning)]">
              <AlertCircle :size="20" />
            </div>
            <div class="min-w-0 flex-1">
              <h3 class="text-base font-semibold text-[var(--text-main)]">关闭 Coding Tools MCP？</h3>
              <p class="mt-1 text-xs leading-5 text-[var(--text-secondary)]">你可以隐藏到托盘继续保持 Runtime，或完全退出应用。</p>
            </div>
            <button class="wb-icon-button !h-7 !w-7 !min-h-7" type="button" @click="open = false"><X :size="13" /></button>
          </div>
          <div class="mt-5 flex justify-end gap-2">
            <button class="tx-btn tx-btn-ghost" type="button" :disabled="busy" @click="open = false">取消</button>
            <button class="tx-btn tx-btn-secondary" type="button" :disabled="busy" @click="run('hide')">隐藏到托盘</button>
            <button class="tx-btn tx-btn-primary" type="button" :disabled="busy" @click="run('quit')">退出应用</button>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.modal-enter-active,
.modal-leave-active { transition: opacity 160ms ease; }
.modal-enter-from,
.modal-leave-to { opacity: 0; }
</style>
