// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Moon, Sun } from "@lucide/svelte";
  import { onMount } from "svelte";

  let dark = $state(true);

  onMount(() => {
    const stored = localStorage.getItem("theme");
    if (stored === "light" || stored === "dark") {
      dark = stored === "dark";
    } else {
      dark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    }
    apply();
  });

  function apply() {
    const theme = dark ? "dark" : "light";
    document.documentElement.setAttribute("data-theme", theme);
    document.documentElement.classList.toggle("dark", dark);
    localStorage.setItem("theme", theme);
  }

  function toggle() {
    dark = !dark;
    apply();
  }
</script>

<button
  type="button"
  class="relative size-8 rounded-lg flex items-center justify-center text-[var(--sidebar-text-muted)] hover:text-[var(--sidebar-text)] hover:bg-[var(--sidebar-surface-hover)] active:scale-[0.92] transition-all cursor-pointer"
  onclick={toggle}
  title={dark ? "切换至浅色模式" : "切换至深色模式"}
  aria-label="切换主题"
>
  <span
    class="transition-transform duration-300 ease-out {dark ? 'rotate-0 scale-100' : 'rotate-90 scale-0 absolute'}"
  >
    <Sun size={15} strokeWidth={2.2} />
  </span>
  <span
    class="transition-transform duration-300 ease-out {!dark ? 'rotate-0 scale-100' : '-rotate-90 scale-0 absolute'}"
  >
    <Moon size={15} strokeWidth={2.2} />
  </span>
</button>

// src/components/ThemeToggle.vue
<script setup lang="ts">
import { Moon, Sun } from "@lucide/vue";
import { onMounted, ref } from "vue";

const dark = ref(false);

function applyTheme(nextDark: boolean) {
  dark.value = nextDark;
  const theme = nextDark ? "dark" : "light";
  document.documentElement.dataset.theme = theme;
  document.documentElement.classList.toggle("dark", nextDark);
  localStorage.setItem("coding-tools-theme", theme);
}

onMounted(() => {
  const saved = localStorage.getItem("coding-tools-theme");
  const initialDark = saved ? saved === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches;
  applyTheme(initialDark);
});
</script>

<template>
  <button
    type="button"
    class="ios-theme-toggle"
    :title="dark ? '切换到浅色模式' : '切换到深色模式'"
    @click="applyTheme(!dark)"
  >
    <Sun v-if="dark" :size="14" />
    <Moon v-else :size="14" />
  </button>
</template>

<style scoped>
.ios-theme-toggle {
  display: grid;
  width: 32px;
  height: 32px;
  flex: 0 0 32px;
  place-items: center;
  border: 1px solid rgba(255,255,255,.72);
  border-radius: 11px;
  background: rgba(255,255,255,.66);
  box-shadow: inset 0 1px 0 rgba(255,255,255,.76), 0 5px 14px rgba(60,72,100,.06);
  color: var(--text-secondary);
  cursor: pointer;
  transition: background 150ms ease, color 150ms ease, transform 150ms ease;
}
.ios-theme-toggle:hover { background: rgba(255,255,255,.9); color: #5e5ce6; }
.ios-theme-toggle:active { transform: scale(.95); }
:global(.dark) .ios-theme-toggle {
  border-color: rgba(255,255,255,.07);
  background: rgba(255,255,255,.055);
  box-shadow: inset 0 1px 0 rgba(255,255,255,.04);
}
</style>
