// src/lib/components/ui/ConfirmDialog.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Modal from "./Modal.svelte";
  import Button from "./Button.svelte";
  import { AlertTriangle, AlertCircle, Info } from "@lucide/svelte";

  interface Props {
    open: boolean;
    title: string;
    message?: string;
    detail?: string;
    confirmText?: string;
    cancelText?: string;
    severity?: "danger" | "warning" | "info";
    busy?: boolean;
    onConfirm: () => void | Promise<void>;
    onCancel: () => void;
    children?: Snippet;
  }

  let {
    open,
    title,
    message,
    detail,
    confirmText = "确认",
    cancelText = "取消",
    severity = "danger",
    busy = false,
    onConfirm,
    onCancel,
    children,
  }: Props = $props();

  const iconConfig = {
    danger: {
      icon: AlertTriangle,
      bg: "bg-[var(--danger-soft)] text-[var(--danger)] border border-[var(--danger)]/20",
    },
    warning: {
      icon: AlertCircle,
      bg: "bg-[var(--warning-soft)] text-[var(--warning)] border border-[var(--warning)]/20",
    },
    info: {
      icon: Info,
      bg: "bg-[var(--primary-soft)] text-[var(--primary)] border border-[var(--primary)]/20",
    },
  };
</script>

<Modal {open} onclose={onCancel} showClose={!busy} maxWidth="max-w-md">
  {@const currentConfig = iconConfig[severity]}
  {@const Icon = currentConfig.icon}
  <div class="flex items-start gap-3.5">
    <div class="size-10 rounded-xl flex items-center justify-center shrink-0 {currentConfig.bg}">
      <Icon size={20} strokeWidth={2.2} />
    </div>
    <div class="min-w-0 flex-1">
      <h3 class="text-base font-semibold text-[var(--text-main)] leading-snug tracking-tight">
        {title}
      </h3>
      {#if message}
        <p class="text-xs text-[var(--text-secondary)] mt-1.5 leading-relaxed">
          {message}
        </p>
      {/if}
      {#if children}
        <div class="text-xs text-[var(--text-secondary)] mt-1.5 leading-relaxed">
          {@render children()}
        </div>
      {/if}
      {#if detail}
        <div class="mt-2.5 p-2 rounded-lg bg-[var(--surface-hover)] border border-[var(--border)] text-xs text-[var(--text-muted)] font-mono break-all">
          {detail}
        </div>
      {/if}
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-2.5 pt-3 border-t border-[var(--border)]">
    <Button
      variant="ghost"
      size="md"
      disabled={busy}
      onclick={onCancel}
    >
      {cancelText}
    </Button>
    <Button
      variant={severity === "danger" ? "danger" : "primary"}
      size="md"
      {busy}
      onclick={onConfirm}
    >
      {confirmText}
    </Button>
  </div>
</Modal>

// src/components/ui/ConfirmDialog.vue
<script setup lang="ts">
import { AlertTriangle } from "@lucide/vue";
import BaseButton from "$src/components/ui/BaseButton.vue";
import ModalDialog from "$src/components/ui/ModalDialog.vue";

withDefaults(defineProps<{
  open: boolean;
  title: string;
  message?: string;
  detail?: string;
  confirmText?: string;
  cancelText?: string;
  severity?: "warning" | "danger" | "info";
  busy?: boolean;
}>(), {
  confirmText: "确认",
  cancelText: "取消",
  severity: "warning",
  busy: false,
});

defineEmits<{ confirm: []; cancel: [] }>();
</script>

<template>
  <ModalDialog :open="open" @close="$emit('cancel')">
    <div class="flex items-start gap-3">
      <div class="grid h-10 w-10 shrink-0 place-items-center rounded-2xl" :class="severity === 'danger' ? 'bg-red-500/12 text-[var(--danger)]' : 'bg-amber-500/12 text-[var(--warning)]'">
        <AlertTriangle :size="19" />
      </div>
      <div class="min-w-0 flex-1">
        <h3 class="text-base font-semibold text-[var(--text-main)]">{{ title }}</h3>
        <p v-if="message" class="mt-1 text-sm leading-6 text-[var(--text-secondary)]">{{ message }}</p>
        <p v-if="detail" class="mt-2 break-all rounded-xl bg-black/4 px-3 py-2 font-mono text-[11px] text-[var(--text-muted)] dark:bg-white/5">{{ detail }}</p>
        <slot />
      </div>
    </div>
    <div class="mt-5 flex justify-end gap-2">
      <BaseButton variant="ghost" :disabled="busy" @click="$emit('cancel')">{{ cancelText }}</BaseButton>
      <BaseButton :variant="severity === 'danger' ? 'danger' : 'primary'" :busy="busy" @click="$emit('confirm')">{{ confirmText }}</BaseButton>
    </div>
  </ModalDialog>
</template>
